### ISSUE TITLE
qemu version has changed to 9.8

### ISSUE THREAD

**Issue by jwag59** [NaohiroTamura/cross-sms-aarch64.sh#1]
The make base_os=centos8 fails since teh qemu version on the ubuntu site has changed. It has moved from 9.7 to 9.8.
Can you please update the Makefile to reflect this?
The modification I made was:

```
# define variables
#   UPDATED QEMU_USER_STATIC_DEB_FILE := qemu-user-static_4.0+dfsg-0ubuntu9.7_amd64.deb
QEMU_USER_STATIC_DEB_FILE := qemu-user-static_4.0+dfsg-0ubuntu9.8_amd64.deb
```

**Comment by NaohiroTamura** [comment]
@jwag59 thanks!
