### ISSUE TITLE
qemu version has changed once again so the make aborts. 

### ISSUE THREAD

**Issue by jwag59** [NaohiroTamura/cross-sms-aarch64.sh#8]
The qemu version available in the Ubuntu repository has once again changed. The version specified in the Makefile no longer exists. The following error is reported if you try to run 'make':

```
[root@pmtest cross-sms-aarch64.sh-master]# make base_os=centos8
wget http://security.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_4.0+dfsg-0ubuntu9.8_amd64.deb
--2021-03-01 07:39:57--  http://security.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_4.0+dfsg-0ubuntu9.8_amd64.deb
Resolving security.ubuntu.com (security.ubuntu.com)... 91.189.91.39, 91.189.91.38, 91.189.88.142, ...
Connecting to security.ubuntu.com (security.ubuntu.com)|91.189.91.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-01 07:39:58 ERROR 404: Not Found.

make: *** [Makefile:74: usr/bin/qemu-aarch64-static] Error 8
```

A version of qemu-user-static that is in the repo and works is:
qemu-user-static_2.5+dfsg-5ubuntu10.51_amd64.deb

I know it is not good practice, but perhaps you could consider adding a working version of qemu-user-static to your distribution rather than trying to download a specific version that clearly becomes out of date quite quickly. 
At least this way the make would always work.

**Comment by NaohiroTamura** [comment]
@jwag59, thank you for testing and reporting it again.
I agree with you to add deb package.
So please find the patch above. I'm sure that qemu-user-static_2.5+dfsg-5ubuntu10.51_amd64.deb works, but chose qemu-user-static_4.2-3ubuntu6.14_amd64.deb that focal (20.04LTS) contains.
Thanks!
